version: '3.8'  

services:  
  mongodb:  
    image: mongo:latest  
    container_name: mongodb  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/data/db  

  mqtt:  
    image: eclipse-mosquitto:latest  
    container_name: mqtt  
    ports:  
      - "1883:1883"  
      - "9001:9001"  

  data_adapter:  
    build: ./adapter  
    container_name: data_adapter  
    depends_on:  
      - mongodb  
      - mqtt  
    environment:  
      - MONGO_URI=mongodb://mongodb:27017/  
      - MQTT_BROKER=mqtt://mqtt:1883  

  ai4triage:  
    build: ./ai4triage  
    container_name: ai4triage  
    depends_on:  
      - mongodb  
      - mqtt  

  nodered:  
    build: ./nodered  
    container_name: nodered  
    ports:  
      - "1880:1880"  
    volumes:  
      - nodered_data:/data  
    depends_on:  
      - mongodb  
      - mqtt  

volumes:  
  mongodb_data:  
  nodered_data:  
